version: '3'

services:
  app:
    build:
      context: .
    environment:
      NODE_ENV: development
    depends_on:
      - db
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/app
      - /app/node_modules
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./server/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
