version: '3'

services:
  app:
    build:
      context: .
    entrypoint: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm run development'
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/app
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./server/initdb:/docker-entrypoint-initdb.d