query BillDetail($billId: Int!) {
    billById(id: $billId) {
        id
        name
        amount
        ownerId
        createdAt
        participatingUsers {
            nodes {
                id
                bestIdentifier
                firstName
                userBillStatusByBillId(billId: $billId) {
                    percent
                    paid
                }
            }
        }
    }
}