query GroupDetail($groupId: Int!) {
    groupById(id: $groupId) {
        id
        owner {
            id
            bestIdentifier
        }
        members {
            nodes {
                id
                bestIdentifier
            }
        }
        billsByGroupId(orderBy: CREATED_AT_DESC) {
            nodes {
                id
                name
                amount
                createdAt
                userByOwnerId {
                    id
                    bestIdentifier
                }
            }
        }
    }
}