query GroupDetail($groupId: Int!) {
    groupById(id: $groupId) {
        id
        userByOwnerId {
            id
            username
        }
        members {
            nodes {
                id
                username
            }
        }
        billsByGroupId(orderBy: CREATED_AT_DESC) {
            nodes {
                id
                name
                amount
                createdAt
                userByOwnerId {
                    id
                    username
                }
            }
        }
    }
}