query Groups {
    currentPerson {
        id
        participatingGroups {
            nodes {
                id
                name
                userByOwnerId {
                    id
                    username
                }
            }
        }
    }
}