query Groups {
    currentPerson {
        id
        participatingGroups {
            nodes {
                id
                name
                owner {
                    id
                    bestIdentifier
                }
            }
        }
    }
}